version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 

  rabbitmq: 
    image: rabbitmq:3.13-management 
    ports: 
      - "5672:5672" 
      - "15672:15672" 
    
    

  web:
    build: .
    command:  ["sh", "-c", "python ecommerce/manage.py migrate && python ecommerce/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/test_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0 

  # celery:
  #   build: .
  #   command: | 
  #     celery -A ecommerce.ecommerce.celeryapp worker --loglevel=info 
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     - DATABASE_URL=postgres://postgres:admin@db:5432/test_db
  #     - REDIS_URL=redis://redis:6379/0
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data: