name: Django CI with Docker Compose

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Start services using Docker Compose
      run: docker-compose up -d

    # - name: Download wait-for-it.sh
    #   run: curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh

    # - name: Make wait-for-it.sh executable
    #   run: chmod +x wait-for-it.sh

    # - name: Wait for services to be ready
    #   run: ./wait-for-it.sh db:5432 --timeout=60 --strict -- echo "Database is up"

    - name: Install dependencies
      run: |
        docker-compose exec web python -m pip install --upgrade pip
        docker-compose exec web pip install -r requirements.txt

    - name: Run migrations
      run: docker-compose exec web python manage.py migrate

    - name: Run tests
      run: docker-compose exec web python manage.py test

    - name: Stop services
      if: always()
      run: docker-compose down